# Generated by Django 5.1.3 on 2025-06-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manzil')),
                ('time', models.CharField(blank=True, max_length=150, null=True, verbose_name='Vaqt')),
                ('price', models.CharField(blank=True, max_length=150, null=True, verbose_name='Narx')),
                ('type', models.CharField(blank=True, choices=[('tour', 'Tour'), ('hotel', 'Hotel'), ('transfer', 'Transfer')], default='tour', max_length=150, null=True, verbose_name='Turi')),
                ('status', models.CharField(blank=True, choices=[('open', 'Ochiq'), ('close', 'Yopiq')], default='open', max_length=100, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'TravelModel',
                'verbose_name_plural': 'TravelModels',
                'db_table': 'travel',
            },
        ),
    ]
