# Generated by Django 5.1.3 on 2025-06-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_travelmodel_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Ism')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telefon')),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('vise', 'Visa')], default='payme', max_length=100, verbose_name="To'lov turi")),
                ('quantity', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Chipta Soni')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'OrderModel',
                'verbose_name_plural': 'OrderModels',
                'db_table': 'order',
            },
        ),
    ]
