# Generated by Django 5.1.3 on 2025-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ism && Familya')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(verbose_name='Telefon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'ContactModel',
                'verbose_name_plural': 'ContactModels',
                'db_table': 'contact',
            },
        ),
    ]
